# Combined results tables for the four targets and both cohorts

Reads the four per-target CSVs produced by `MDC_calculation_and_SEM_analysis.ipynb`
(`MDC_results/{target}.csv` for `language`, `memory`, `executive_function`, `speed`)
and combines them into latex tables per cohort.

In [2]:
import json

import pandas as pd
from pandas import MultiIndex, IndexSlice
from datetime import datetime
now = lambda: datetime.now().strftime("%Y-%m-%d %H:%M")

all_targets = ['language', 'memory', 'executive_function', 'speed']

target_renaming = {
    'language': 'Language',
    'executive_function': 'Executive Function',
    'speed': 'Speed',
    'memory': 'Memory'
}
task_renaming = {
    'cookieTheft': 'Cookie Theft',
    'picnicScene': 'Picnic Scene',
    'journaling': 'Journaling',
    'avg_speech_prediction': 'Avg. Speech Prediction',
}

In [4]:
dfs = {}
for target in all_targets:
    df = pd.read_csv(f'MDC_results/{target}.csv', index_col=0)
    df.columns = [f"Cohort {c}" for c in df.columns]
    df.index = [idx.replace("_"+target, "") for idx in df.index]
    dfs[target] = df

combined = pd.concat(dfs, axis=1).sort_index(axis=1, level=1)
combined

,executive_function,language,memory,speed,executive_function,language,memory,speed
,Cohort A,Cohort A,Cohort A,Cohort A,Cohort B,Cohort B,Cohort B,Cohort B
target,executive_function,language,memory,speed,executive_function,language,memory,speed
n,305,305,305,305,70,70,70,70
ICC,0.7090817899414337,0.6859887459797817,0.6811670870145479,0.7627465006939518,0.8105163262931746,0.7181659156210343,0.7605395940779949,0.8670669635763721
ICC_cookieTheft,0.612511630300788,0.6497343346225238,0.7768229989465425,0.5984895278610916,0.7948860851782574,0.7527766532635288,0.8171744576187923,0.7319398794412624
ICC_picnicScene,0.6844458563674123,0.7545164981722163,0.8354284386924039,0.6816714944991913,0.8679617218414264,0.8390134035725514,0.8847492876252298,0.8647913191204449
...,...,...,...,...,...,...,...,...
avg_speech_prediction_noninferiority_p_value,0.741,NaN,0.087,1.0,0.465,NaN,0.035,0.986
avg_cookieTheft_picnicScene_noninferiority_margin,0.5,NaN,0.5,0.5,0.5,NaN,0.5,0.5
avg_cookieTheft_picnicScene_noninferiority_ci_low,0.4084213371704294,NaN,-0.21587623961915334,1.4904337062228634,-0.25908799083910494,NaN,-0.23508602194855371,0.7242401815005899
avg_cookieTheft_picnicScene_noninferiority_ci_high,1.4409364471207946,NaN,0.6521457283307716,3.2894130423524337,1.3529043128830043,NaN,0.7031587753581181,8.035405881895684
avg_cookieTheft_picnicScene_noninferiority_p_value,0.911,NaN,0.126,1.0,0.4,NaN,0.115,0.977

In [5]:
combined.columns

MultiIndex([('executive_function', 'Cohort A'),
            (          'language', 'Cohort A'),
            (            'memory', 'Cohort A'),
            (             'speed', 'Cohort A'),
            ('executive_function', 'Cohort B'),
            (          'language', 'Cohort B'),
            (            'memory', 'Cohort B'),
            (             'speed', 'Cohort B')],
           )

In [6]:

tasks = ['cookieTheft', 'picnicScene', 'journaling', 'avg_speech_prediction']
cohorts = ['Cohort A', 'Cohort B']
indices_to_keep = []
for cohort in cohorts:
    for task in tasks:
        indices_to_keep.extend([
            f"{task}_mdc_cognitive_text",
            f"{task}_mdc_speech_latent",
            #f"{task}_mdc_speech_pred",
        ])

    combined_subset = combined.loc[indices_to_keep, pd.IndexSlice[:, cohort]]
    combined_subset.columns = combined_subset.columns.droplevel(1)
    print(combined_subset.to_latex())

    break

\begin{tabular}{lllll}
\toprule
 & executive_function & language & memory & speed \\
\midrule
cookieTheft_mdc_cognitive_text & 1.46 (1.28-1.63) & 1.48 (1.29-1.67) & 1.65 (1.47-1.80) & 1.28 (1.13-1.42) \\
cookieTheft_mdc_speech_latent & 3.43 (2.65-4.58) & 2.43 (1.93-3.13) & 2.49 (1.97-3.31) & 5.21 (3.72-7.68) \\
picnicScene_mdc_cognitive_text & 1.46 (1.29-1.62) & 1.48 (1.29-1.66) & 1.65 (1.47-1.82) & 1.28 (1.12-1.41) \\
picnicScene_mdc_speech_latent & 2.56 (2.06-3.26) & 1.88 (1.53-2.32) & 2.08 (1.59-2.80) & 3.54 (2.74-4.77) \\
journaling_mdc_cognitive_text & 1.46 (1.29-1.63) & 1.48 (1.29-1.67) & 1.65 (1.47-1.81) & 1.28 (1.12-1.42) \\
journaling_mdc_speech_latent & 3.46 (2.72-4.59) & 2.86 (2.27-3.66) & 3.02 (2.25-4.32) & 4.93 (3.50-7.52) \\
avg_speech_prediction_mdc_cognitive_text & 1.46 (1.30-1.64) & 1.48 (1.29-1.67) & 1.65 (1.48-1.81) & 1.28 (1.13-1.42) \\
avg_speech_prediction_mdc_speech_latent & 2.15 (1.73-2.73) & 1.61 (1.32-1.96) & 1.72 (1.35-2.36) & 3.29 (2.46-4.50) \\
\bottomrule
\end{tabular}

In [7]:

tasks = ['cookieTheft', 'picnicScene', 'journaling', 'avg_speech_prediction']
cohorts = ['Cohort A', 'Cohort B']
indices_to_keep = []
for cohort in cohorts:
    for task in tasks:
        indices_to_keep.extend([
            f"{task}_significance",
            #f"{task}_mdc_speech_pred",
        ])

    combined_subset = combined.loc[indices_to_keep, pd.IndexSlice[:, cohort]]
    combined_subset.columns = combined_subset.columns.droplevel(1)
    print(combined_subset.to_latex())

    break

\begin{tabular}{lllll}
\toprule
 & executive_function & language & memory & speed \\
\midrule
cookieTheft_significance & 1.2-3.2* & 0.37-1.7* & 0.27-1.7* & 2.4-6.4* \\
picnicScene_significance & 0.55-1.8* & -0.061-0.94 & -0.096-1.2 & 1.5-3.5* \\
journaling_significance & 1.2-3.2* & 0.69-2.3* & 0.58-2.7* & 2.2-6.3* \\
avg_speech_prediction_significance & 0.18-1.3* & -0.28-0.59 & -0.33-0.74 & 1.1-3.3* \\
\bottomrule
\end{tabular}

In [8]:

tasks = ['cookieTheft', 'picnicScene', 'journaling']
cohorts = ['Cohort A', 'Cohort B']
combined_tasks = []

def combine_metrics(series):
    display(series)
    task = list(series.index)[0].split("_")[0]
    aggregated = pd.Series({task: "/".join(series.round(2).astype(str))}, name=series.name)
    return aggregated


for cohort in cohorts:
    for task in tasks:
        combined_task_separate = combined.loc[[
            f"{task}_sem_tli",
            f"{task}_sem_cfi",
            f"{task}_sem_srmr",
            #f"{task}_sem_chi2",
        ], pd.IndexSlice[:, cohort]].astype(float)
        combined_task_separate.columns = combined_task_separate.columns.droplevel(1)
        combined_task = combined_task_separate.apply(combine_metrics, axis=0)
        combined_tasks.append(combined_task)

    combined_subset = pd.concat(combined_tasks, axis=0)[all_targets].rename(columns=target_renaming)
    combined_subset.index = [task_renaming.get(c,c) for c in combined_subset.index]
    display(combined_subset)

    break

cookieTheft_sem_tli     1.013401
cookieTheft_sem_cfi     1.008375
cookieTheft_sem_srmr    0.022336
Name: executive_function, dtype: float64

cookieTheft_sem_tli     0.995476
cookieTheft_sem_cfi     0.997173
cookieTheft_sem_srmr    0.046014
Name: language, dtype: float64

cookieTheft_sem_tli     0.967180
cookieTheft_sem_cfi     0.979488
cookieTheft_sem_srmr    0.064401
Name: memory, dtype: float64

cookieTheft_sem_tli     1.006673
cookieTheft_sem_cfi     1.004171
cookieTheft_sem_srmr    0.015651
Name: speed, dtype: float64

picnicScene_sem_tli     1.004505
picnicScene_sem_cfi     1.002816
picnicScene_sem_srmr    0.019033
Name: executive_function, dtype: float64

picnicScene_sem_tli     0.959698
picnicScene_sem_cfi     0.974811
picnicScene_sem_srmr    0.024692
Name: language, dtype: float64

picnicScene_sem_tli     0.973171
picnicScene_sem_cfi     0.983232
picnicScene_sem_srmr    0.062545
Name: memory, dtype: float64

picnicScene_sem_tli     1.000354
picnicScene_sem_cfi     1.000221
picnicScene_sem_srmr    0.026805
Name: speed, dtype: float64

journaling_sem_tli     0.957201
journaling_sem_cfi     0.973251
journaling_sem_srmr    0.044199
Name: executive_function, dtype: float64

journaling_sem_tli     0.916122
journaling_sem_cfi     0.947576
journaling_sem_srmr    0.045393
Name: language, dtype: float64

journaling_sem_tli     0.975940
journaling_sem_cfi     0.984963
journaling_sem_srmr    0.061032
Name: memory, dtype: float64

journaling_sem_tli     0.970741
journaling_sem_cfi     0.981713
journaling_sem_srmr    0.023419
Name: speed, dtype: float64

,Language,Memory,Executive Function,Speed
Cookie Theft,1.0/1.0/0.05,0.97/0.98/0.06,1.01/1.01/0.02,1.01/1.0/0.02
Picnic Scene,0.96/0.97/0.02,0.97/0.98/0.06,1.0/1.0/0.02,1.0/1.0/0.03
Journaling,0.92/0.95/0.05,0.98/0.98/0.06,0.96/0.97/0.04,0.97/0.98/0.02

In [9]:
tasks = ['cookieTheft', 'picnicScene', 'journaling']
cohorts = ['Cohort A', 'Cohort B']
metric_keys = ['sem_tli', 'sem_cfi', 'sem_srmr']
metric_names = ['TLI', 'CFI', 'SRMR']

for cohort in cohorts:
    combined_tasks = []

    for task in tasks:
        row = combined.loc[
            [f"{task}_{m}" for m in metric_keys],
            pd.IndexSlice[all_targets, cohort]
        ].astype(float)
        row.columns = row.columns.droplevel(1)
        row.index = metric_names
        # row: (metric x target) -> transpose to (target x metric)
        row = row.T
        # build one row with (target, metric) MultiIndex columns
        tuples = [(target, metric) for target in row.index for metric in metric_names]
        values = row.values.flatten()
        combined_tasks.append(
            pd.DataFrame(
                [values],
                index=[task_renaming.get(task, task)],
                columns=pd.MultiIndex.from_tuples(tuples)
            )
        )

    combined_subset = pd.concat(combined_tasks)
    combined_subset.columns = pd.MultiIndex.from_tuples(
        [(target_renaming.get(t, t), m) for t, m in combined_subset.columns],
        names=[None, None]
    )

    combined_subset_latex = combined_subset.to_latex(float_format="%.2f", multirow=True, multicolumn=True, multicolumn_format="c", column_format="l" + "c" * len(combined_subset.columns),
                                                     caption=f"Absolute fit indices of the speech measurement model for each speech task and composite score for {cohort}. CFI and TLI above 0.95 and SRMR below 0.08 indicate adequate fit. Fit indices for the five alternative models and the corresponding likelihood-ratio tests are reported in the supplementary material (Tables~\\ref{{tab:sem_fit_cohortA}} and \\ref{{tab:sem_lr_cohortA}}).")
    print(f"% === {cohort}: full-model summary {cohort} ({now()}) ===")
    print(combined_subset_latex)

% === Cohort A: full-model summary Cohort A (2026-09-22 11:26) ===
\begin{table}
\caption{Absolute fit indices of the speech measurement model for each speech task and composite score for Cohort A. CFI and TLI above 0.95 and SRMR below 0.08 indicate adequate fit. Fit indices for the five alternative models and the corresponding likelihood-ratio tests are reported in the supplementary material (Tables~\ref{tab:sem_fit_cohortA} and \ref{tab:sem_lr_cohortA}).}
\begin{tabular}{lcccccccccccc}
\toprule
 & \multicolumn{3}{c}{Language} & \multicolumn{3}{c}{Memory} & \multicolumn{3}{c}{Executive Function} & \multicolumn{3}{c}{Speed} \\
 & TLI & CFI & SRMR & TLI & CFI & SRMR & TLI & CFI & SRMR & TLI & CFI & SRMR \\
\midrule
Cookie Theft & 1.00 & 1.00 & 0.05 & 0.97 & 0.98 & 0.06 & 1.01 & 1.01 & 0.02 & 1.01 & 1.00 & 0.02 \\
Picnic Scene & 0.96 & 0.97 & 0.02 & 0.97 & 0.98 & 0.06 & 1.00 & 1.00 & 0.02 & 1.00 & 1.00 & 0.03 \\
Journaling & 0.92 & 0.95 & 0.05 & 0.98 & 0.98 & 0.06 & 0.96 & 0.97 & 0.04 & 0.97 & 0.98 & 0.02 \\
\bottomrule
\end{tabular}
\end{table}

% === Cohort B: full-model summary Cohort B (2026-09-22 11:26) ===
\begin{table}
\caption{Absolute fit indices of the speech measurement model for each speech task and composite score for Cohort B. CFI and TLI above 0.95 and SRMR below 0.08 indicate adequate fit. Fit indices for the five alternative models and the corresponding likelihood-ratio tests are reported in the supplementary material (Tables~\ref{tab:sem_fit_cohortA} and \ref{tab:sem_lr_cohortA}).}
\begin{tabular}{lcccccccccccc}
\toprule
 & \multicolumn{3}{c}{Language} & \multicolumn{3}{c}{Memory} & \multicolumn{3}{c}{Executive Function} & \multicolumn{3}{c}{Speed} \\
 & TLI & CFI & SRMR & TLI & CFI & SRMR & TLI & CFI & SRMR & TLI & CFI & SRMR \\
\midrule
Cookie Theft & 1.03 & 1.02 & 0.03 & 1.01 & 1.01 & 0.04 & 0.97 & 0.98 & 0.06 & 0.99 & 1.00 & 0.05 \\
Picnic Scene & 1.03 & 1.02 & 0.02 & 0.99 & 0.99 & 0.05 & 0.99 & 1.00 & 0.05 & 1.02 & 1.01 & 0.03 \\
Journaling & 1.01 & 1.00 & 0.06 & 1.01 & 1.01 & 0.03 & 0.94 & 0.96 & 0.06 & 0.95 & 0.97 & 0.09 \\
\bottomrule
\end{tabular}
\end{table}

In [10]:
from io import StringIO
import json


def format_num(x, decimals=3):
    if pd.isna(x):
        return "---"
    return f"{x:.{decimals}f}"

def format_p(p):
    """Format p-values: '<0.001' for very small, else 3 decimals."""
    if pd.isna(p):
        return "---"
    if p < 0.001:
        return "$<0.001$"
    return f"{p:.3f}"


task_display_names = {
    "cookieTheft":                 r"Cookie Theft",
    "picnicScene":                 r"Picnic Scene",
    "journaling":                  r"Journaling",
    "avg_speech_prediction":       r"Avg.\ (all tasks)",
    "avg_cookieTheft_picnicScene": r"Avg.\ (Cookie Theft + Picnic Scene)",
}

def combined_lr_table_to_latex(
    results_df,
    cohort='Cohort A',
    targets=('language', 'memory', 'executive_function', 'speed'),
    label='tab:sem_lr_cohortA_all_targets',
    caption=None,
):
    """
    Create a wide LR-test LaTeX table with one 3-column block per target:
        Δχ² | Δdf | p

    Rows:
        task × comparison
    """

    comparison_display = {
        'no_attenuation vs full':         r'$\lambda=1$ vs.\ Full',
        'no_beta vs full':                r'No $\beta$ vs.\ Full',
        'no_attenuation_no_beta vs full': r'$\lambda=1$, no $\beta$ vs.\ Full',
        'full vs free_hat_resid_by_wave': r'Full vs.\ free $\sigma_\epsilon^2$ by wave',
        'full vs free_y_resid_by_wave':   r'Full vs.\ free $\sigma_\delta^2$ by wave',
    }

    # ------------------------------------------------------------
    # Parse all target LR dfs
    # ------------------------------------------------------------
    lr_by_target = {}

    for target in all_targets:

        # json-encoded dataframe string
        #print((target, cohort), 'cookieTheft_sem_lr_full')
        #print(results_df.loc[:, (target, cohort)].index.tolist())
        raw = results_df.loc['cookieTheft_sem_lr_full', (target, cohort)]

        # if your actual column is different, replace above with:
        # raw = results_df.loc[(target, cohort), 'sem_lr_json']

        lr_df_text = json.loads(raw)
        lr_df = pd.DataFrame(
            data=lr_df_text["data"],
            columns=lr_df_text["columns"]
        )
        lr_df.index = pd.MultiIndex.from_tuples(
            lr_df_text["index"],
            names=["Task", "Comparison"]
        )

        lr_by_target[target] = lr_df.copy()

    # ------------------------------------------------------------
    # Build unified row index from first target
    # ------------------------------------------------------------
    base_index = lr_by_target[targets[0]].index

    out = pd.DataFrame(index=base_index)

    # ------------------------------------------------------------
    # Add formatted columns for each target
    # ------------------------------------------------------------
    for target in targets:

        df = lr_by_target[target]

        out[(target, r'$\Delta\chi^2$')] = [
            format_num(v, 3)
            for v in df['delta_chi2']
        ]

        out[(target, r'$\Delta$df')] = [
            '---' if pd.isna(v) else f'{int(v)}'
            for v in df['delta_df']
        ]

        out[(target, r'$p$')] = [
            format_p(v)
            for v in df['p_value']
        ]

    # ------------------------------------------------------------
    # Pretty row labels
    # ------------------------------------------------------------
    out.index = pd.MultiIndex.from_tuples(
        [
            (
                task_display_names.get(task, task),
                comparison_display.get(comp, comp),
            )
            for (task, comp) in out.index
        ],
        names=['Task', 'Comparison'],
    )

    # ------------------------------------------------------------
    # Pretty column labels
    # ------------------------------------------------------------
    target_display = {
        'language': r'Language',
        'memory': r'Memory',
        'executive_function': r'Executive function',
        'speed': r'Speed',
    }

    out.columns = pd.MultiIndex.from_tuples([
        (
            target_display.get(target, target),
            stat,
        )
        for (target, stat) in out.columns
    ])

    # ------------------------------------------------------------
    # Column format
    # ll = row index cols
    # then 3 numeric cols per target
    # ------------------------------------------------------------
    column_format = 'll' + ('rrr' * len(targets))

    # ------------------------------------------------------------
    # Caption
    # ------------------------------------------------------------
    if caption is None:
        caption = (
            f"{cohort}: likelihood-ratio tests for the nested model comparisons across all cognitive target scores. For the three nested alternatives (top three rows per task), a significant $p$-value rejects the alternative in favor of the full model. For the two stationarity relaxations (bottom two rows per task), a non-significant $p$-value is consistent with stationary residual variances."
        )

    # ------------------------------------------------------------
    # Export LaTeX
    # ------------------------------------------------------------
    latex = out.to_latex(
        escape=False,
        multicolumn=True,
        multirow=True,
        column_format=column_format,
        caption=caption,
        label=label,
    )

    latex = latex.replace(r'\cline', r'\cmidrule')

    return latex


latex = combined_lr_table_to_latex(
    results_df=combined,
    cohort='Cohort A',
    label='tab:sem_lr_cohortA',
)

print(f"% === Cohort A: LR tests {now()} ===")
print(latex)

% === Cohort A: LR tests 2026-09-22 11:26 ===
\begin{table}
\caption{Cohort A: likelihood-ratio tests for the nested model comparisons across all cognitive target scores. For the three nested alternatives (top three rows per task), a significant $p$-value rejects the alternative in favor of the full model. For the two stationarity relaxations (bottom two rows per task), a non-significant $p$-value is consistent with stationary residual variances.}
\label{tab:sem_lr_cohortA}
\begin{tabular}{llrrrrrrrrrrrr}
\toprule
 &  & \multicolumn{3}{r}{Language} & \multicolumn{3}{r}{Memory} & \multicolumn{3}{r}{Executive function} & \multicolumn{3}{r}{Speed} \\
 &  & $\Delta\chi^2$ & $\Delta$df & $p$ & $\Delta\chi^2$ & $\Delta$df & $p$ & $\Delta\chi^2$ & $\Delta$df & $p$ & $\Delta\chi^2$ & $\Delta$df & $p$ \\
Task & Comparison &  &  &  &  &  &  &  &  &  &  &  &  \\
\midrule
\multirow[t]{5}{*}{Cookie Theft} & $\lambda=1$ vs.\ Full & 128.155 & 1 & $<0.001$ & 141.427 & 1 & $<0.001$ & 167.824 & 1 & $<0.001$ & 226.943 & 1 & $<0.001$ \\
 & No $\beta$ vs.\ Full & 78.453 & 1 & $<0.001$ & 135.023 & 1 & $<0.001$ & 92.510 & 1 & $<0.001$ & 108.939 & 1 & $<0.001$ \\
 & $\lambda=1$, no $\beta$ vs.\ Full & 128.155 & 2 & $<0.001$ & 141.786 & 2 & $<0.001$ & 167.824 & 2 & $<0.001$ & 227.033 & 2 & $<0.001$ \\
 & Full vs.\ free $\sigma_\epsilon^2$ by wave & 4.565 & 1 & 0.033 & 0.022 & 1 & 0.883 & 1.131 & 1 & 0.288 & 0.009 & 1 & 0.925 \\
 & Full vs.\ free $\sigma_\delta^2$ by wave & 0.340 & 1 & 0.560 & 2.032 & 1 & 0.154 & 0.374 & 1 & 0.541 & 0.007 & 1 & 0.932 \\
\cmidrule{1-14}
\multirow[t]{5}{*}{Picnic Scene} & $\lambda=1$ vs.\ Full & 122.495 & 1 & $<0.001$ & 139.283 & 1 & $<0.001$ & 158.714 & 1 & $<0.001$ & 219.267 & 1 & $<0.001$ \\
 & No $\beta$ vs.\ Full & 108.024 & 1 & $<0.001$ & 137.495 & 1 & $<0.001$ & 113.399 & 1 & $<0.001$ & 148.013 & 1 & $<0.001$ \\
 & $\lambda=1$, no $\beta$ vs.\ Full & 122.647 & 2 & $<0.001$ & 140.748 & 2 & $<0.001$ & 158.714 & 2 & $<0.001$ & 219.420 & 2 & $<0.001$ \\
 & Full vs.\ free $\sigma_\epsilon^2$ by wave & 1.001 & 1 & 0.317 & 0.385 & 1 & 0.535 & 0.173 & 1 & 0.677 & 0.223 & 1 & 0.637 \\
 & Full vs.\ free $\sigma_\delta^2$ by wave & 0.155 & 1 & 0.694 & 2.212 & 1 & 0.137 & 0.161 & 1 & 0.688 & 0.222 & 1 & 0.638 \\
\cmidrule{1-14}
\multirow[t]{5}{*}{Journaling} & $\lambda=1$ vs.\ Full & 124.765 & 1 & $<0.001$ & 146.403 & 1 & $<0.001$ & 163.561 & 1 & $<0.001$ & 225.620 & 1 & $<0.001$ \\
 & No $\beta$ vs.\ Full & 64.554 & 1 & $<0.001$ & 146.196 & 1 & $<0.001$ & 65.019 & 1 & $<0.001$ & 93.007 & 1 & $<0.001$ \\
 & $\lambda=1$, no $\beta$ vs.\ Full & 124.959 & 2 & $<0.001$ & 148.438 & 2 & $<0.001$ & 163.562 & 2 & $<0.001$ & 226.211 & 2 & $<0.001$ \\
 & Full vs.\ free $\sigma_\epsilon^2$ by wave & 3.142 & 1 & 0.076 & 1.599 & 1 & 0.206 & 0.125 & 1 & 0.724 & 0.249 & 1 & 0.618 \\
 & Full vs.\ free $\sigma_\delta^2$ by wave & 0.313 & 1 & 0.576 & 3.131 & 1 & 0.077 & 0.183 & 1 & 0.669 & 0.020 & 1 & 0.888 \\
\cmidrule{1-14}
\bottomrule
\end{tabular}
\end{table}

In [11]:
latex = combined_lr_table_to_latex(
    results_df=combined,
    cohort='Cohort B',
    label='tab:sem_lr_cohortB',
)

print(f"% === Cohort B: LR tests {now()} ===")
print(latex)

% === Cohort B: LR tests 2026-09-22 11:26 ===
\begin{table}
\caption{Cohort B: likelihood-ratio tests for the nested model comparisons across all cognitive target scores. For the three nested alternatives (top three rows per task), a significant $p$-value rejects the alternative in favor of the full model. For the two stationarity relaxations (bottom two rows per task), a non-significant $p$-value is consistent with stationary residual variances.}
\label{tab:sem_lr_cohortB}
\begin{tabular}{llrrrrrrrrrrrr}
\toprule
 &  & \multicolumn{3}{r}{Language} & \multicolumn{3}{r}{Memory} & \multicolumn{3}{r}{Executive function} & \multicolumn{3}{r}{Speed} \\
 &  & $\Delta\chi^2$ & $\Delta$df & $p$ & $\Delta\chi^2$ & $\Delta$df & $p$ & $\Delta\chi^2$ & $\Delta$df & $p$ & $\Delta\chi^2$ & $\Delta$df & $p$ \\
Task & Comparison &  &  &  &  &  &  &  &  &  &  &  &  \\
\midrule
\multirow[t]{5}{*}{Cookie Theft} & $\lambda=1$ vs.\ Full & 35.101 & 1 & $<0.001$ & 46.940 & 1 & $<0.001$ & 60.191 & 1 & $<0.001$ & 90.980 & 1 & $<0.001$ \\
 & No $\beta$ vs.\ Full & 14.424 & 1 & $<0.001$ & 60.594 & 1 & $<0.001$ & 57.504 & 1 & $<0.001$ & 49.978 & 1 & $<0.001$ \\
 & $\lambda=1$, no $\beta$ vs.\ Full & 35.101 & 2 & $<0.001$ & 47.770 & 2 & $<0.001$ & 62.167 & 2 & $<0.001$ & 92.077 & 2 & $<0.001$ \\
 & Full vs.\ free $\sigma_\epsilon^2$ by wave & 0.517 & 1 & 0.472 & 1.579 & 1 & 0.209 & 0.171 & 1 & 0.679 & 0.004 & 1 & 0.948 \\
 & Full vs.\ free $\sigma_\delta^2$ by wave & 0.599 & 1 & 0.439 & 0.103 & 1 & 0.748 & 0.456 & 1 & 0.499 & 0.868 & 1 & 0.351 \\
\cmidrule{1-14}
\multirow[t]{5}{*}{Picnic Scene} & $\lambda=1$ vs.\ Full & 28.552 & 1 & $<0.001$ & 41.827 & 1 & $<0.001$ & 54.052 & 1 & $<0.001$ & 88.909 & 1 & $<0.001$ \\
 & No $\beta$ vs.\ Full & 19.435 & 1 & $<0.001$ & 43.907 & 1 & $<0.001$ & 78.766 & 1 & $<0.001$ & 91.442 & 1 & $<0.001$ \\
 & $\lambda=1$, no $\beta$ vs.\ Full & 28.552 & 2 & $<0.001$ & 44.141 & 2 & $<0.001$ & 58.884 & 2 & $<0.001$ & 93.137 & 2 & $<0.001$ \\
 & Full vs.\ free $\sigma_\epsilon^2$ by wave & 0.311 & 1 & 0.577 & 4.712 & 1 & 0.030 & 0.036 & 1 & 0.849 & 0.042 & 1 & 0.838 \\
 & Full vs.\ free $\sigma_\delta^2$ by wave & 0.813 & 1 & 0.367 & 0.322 & 1 & 0.571 & 0.445 & 1 & 0.505 & 0.562 & 1 & 0.453 \\
\cmidrule{1-14}
\multirow[t]{5}{*}{Journaling} & $\lambda=1$ vs.\ Full & 34.382 & 1 & $<0.001$ & 42.836 & 1 & $<0.001$ & 63.373 & 1 & $<0.001$ & 91.392 & 1 & $<0.001$ \\
 & No $\beta$ vs.\ Full & 27.934 & 1 & $<0.001$ & 44.219 & 1 & $<0.001$ & 41.780 & 1 & $<0.001$ & 41.391 & 1 & $<0.001$ \\
 & $\lambda=1$, no $\beta$ vs.\ Full & 34.382 & 2 & $<0.001$ & 44.602 & 2 & $<0.001$ & 65.613 & 2 & $<0.001$ & 92.970 & 2 & $<0.001$ \\
 & Full vs.\ free $\sigma_\epsilon^2$ by wave & 1.931 & 1 & 0.165 & 0.492 & 1 & 0.483 & 0.319 & 1 & 0.572 & 3.055 & 1 & 0.081 \\
 & Full vs.\ free $\sigma_\delta^2$ by wave & 1.043 & 1 & 0.307 & 0.006 & 1 & 0.939 & 0.187 & 1 & 0.666 & 0.576 & 1 & 0.448 \\
\cmidrule{1-14}
\bottomrule
\end{tabular}
\end{table}

In [12]:
import pandas as pd

TASK_ORDER = ['journaling', 'cookieTheft', 'picnicScene', 'avg_speech_prediction']
TASK_DISPLAY = {
    'cookieTheft': 'Cookie Theft',
    'picnicScene': 'Picnic Scene',
    'journaling': 'Journaling',
    'avg_speech_prediction': 'Avg. Speech Pred.',
}
DOMAIN_ORDER = ['language', 'memory', 'executive_function',  'speed']
DOMAIN_DISPLAY = {
    'executive_function': 'Executive Function',
    'language': 'Language',
    'memory': 'Memory',
    'speed': 'Speed',
}

N_BOOTSTRAP_SAMPLES = 10000


def _melt_combined(combined):
    """Reshape `combined` from
        index = '<task>_bootstrap_<metric>', columns = (domain, cohort)
    to a long dataframe with columns
        cohort, domain, task, mean_diff, ci_low, ci_high, excludes_zero, prop_speech_worse.
    """
    # Split the row index into (task, metric).
    idx = combined.index.to_series().str.extract(r'^(?P<task>.+)_bootstrap_(?P<metric>.+)$')
    tmp = combined.copy()
    tmp.index = pd.MultiIndex.from_frame(idx)

    # Long form: one row per (task, metric, domain, cohort).
    long = tmp.stack(level=[0, 1], future_stack=True).rename('value').reset_index()
    long.columns = ['task', 'metric', 'domain', 'cohort', 'value']

    # Pivot metrics into columns.
    wide = long.pivot_table(
        index=['cohort', 'domain', 'task'],
        columns='metric',
        values='value',
        aggfunc='first',
    ).reset_index()
    wide.columns.name = None

    # Types.
    wide['excludes_zero'] = wide['excludes_zero'].replace("True", 1).replace("False", 0).astype(bool)
    for c in ['mean_diff', 'ci_low', 'ci_high', 'prop_speech_worse']:
        wide[c] = wide[c].astype(float)
    return wide


def _fmt_ci(row):
    s = f"{row['ci_low']:.2f} -- {row['ci_high']:.2f}"
    if row['excludes_zero']:
        s += '*'
    return s


def _fmt_prop(p):
    return f"{p:.1%}".replace('%', r'\%')


def _build_cohort_wide(long_df, cohort_label):
    """Build the (task x (domain, metric)) wide table for a single cohort."""
    sub = long_df[
        (long_df['cohort'] == f'Cohort {cohort_label}')
        & (long_df['task'].isin(TASK_ORDER))
    ].copy()
    sub['ci_str'] = sub.apply(_fmt_ci, axis=1)
    sub['prop_str'] = sub['prop_speech_worse'].apply(_fmt_prop)

    pieces = []
    for domain in DOMAIN_ORDER:
        d = (
            sub[sub['domain'] == domain]
            .set_index('task')[['ci_str', 'prop_str']]
        )
        d.columns = pd.MultiIndex.from_tuples([
            (DOMAIN_DISPLAY[domain], r'95\% CI'),
            (DOMAIN_DISPLAY[domain], r'\% better' ),
        ])
        pieces.append(d)

    wide = pd.concat(pieces, axis=1).loc[TASK_ORDER]
    wide.index = [TASK_DISPLAY[t] for t in wide.index]
    wide.index.name = None
    return wide


def cohort_to_latex(wide, cohort_label, n_bootstrap=N_BOOTSTRAP_SAMPLES):
    column_format = 'l' + 'c' * wide.shape[1]
    body = wide.to_latex(
        column_format=column_format,
        multicolumn=True,
        multicolumn_format='c',
        escape=False,
    )
    caption = (
        f"Bootstrap test results assessing whether the speech-based MDC is significantly larger than the cognitive assessment's MDC on Cohort {cohort_label}. For each task and composite cognitive score, we report the 95\\% CI of the difference (speech MDC minus cognitive MDC) across {n_bootstrap} bootstrap replicates, and the proportion of replicates where the speech MDC is larger (less sensitive) than the cognitive MDC (\\% larger). An asterisk (*) on the CI indicates that the CI excludes zero, i.e. the speech MDC is significantly larger than the cognitive MDC."
    )
    label = f"tab:mdc_bootstrap_cohort{cohort_label}"
    return (
        "\\begin{table}\n"
        f"\\caption{{{caption}}}\n"
        f"\\label{{{label}}}\n"
        f"{body}"
        "\\end{table}\n"
    )


# --- Usage ---------------------------------------------------------------
long_df = _melt_combined(combined)
for cohort in ['A', 'B']:
    wide = _build_cohort_wide(long_df, cohort)
    print(f"\n% === Cohort {cohort}: MDC stats for all composite scores ({now()}) ===")
    print(cohort_to_latex(wide, cohort))

% === Cohort A: MDC stats for all composite scores (2026-09-22 11:27) ===
\begin{table}
\caption{Bootstrap test results assessing whether the speech-based MDC is significantly larger than the cognitive assessment's MDC on Cohort A. For each task and composite cognitive score, we report the 95\% CI of the difference (speech MDC minus cognitive MDC) across 10000 bootstrap replicates, and the proportion of replicates where the speech MDC is larger (less sensitive) than the cognitive MDC (\% larger). An asterisk (*) on the CI indicates that the CI excludes zero, i.e. the speech MDC is significantly larger than the cognitive MDC.}
\label{tab:mdc_bootstrap_cohortA}
\begin{tabular}{lcccccccc}
\toprule
 & \multicolumn{2}{c}{Language} & \multicolumn{2}{c}{Memory} & \multicolumn{2}{c}{Executive Function} & \multicolumn{2}{c}{Speed} \\
 & 95\% CI & \% better & 95\% CI & \% better & 95\% CI & \% better & 95\% CI & \% better \\
\midrule
Journaling & 0.69 -- 2.27* & 100.0\% & 0.58 -- 2.68* & 100.0\% & 1.20 -- 3.18* & 100.0\% & 2.23 -- 6.29* & 100.0\% \\
Cookie Theft & 0.37 -- 1.73* & 100.0\% & 0.27 -- 1.68* & 99.9\% & 1.18 -- 3.20* & 100.0\% & 2.44 -- 6.44* & 100.0\% \\
Picnic Scene & -0.06 -- 0.94 & 95.4\% & -0.10 -- 1.20 & 93.6\% & 0.55 -- 1.83* & 100.0\% & 1.46 -- 3.51* & 100.0\% \\
Avg. Speech Pred. & -0.28 -- 0.59 & 73.6\% & -0.33 -- 0.74 & 62.7\% & 0.18 -- 1.33* & 99.9\% & 1.11 -- 3.28* & 100.0\% \\
\bottomrule
\end{tabular}
\end{table}


% === Cohort B: MDC stats for all composite scores (2026-09-22 11:27) ===
\begin{table}
\caption{Bootstrap test results assessing whether the speech-based MDC is significantly larger than the cognitive assessment's MDC on Cohort B. For each task and composite cognitive score, we report the 95\% CI of the difference (speech MDC minus cognitive MDC) across 10000 bootstrap replicates, and the proportion of replicates where the speech MDC is larger (less sensitive) than the cognitive MDC (\% larger). An asterisk (*) on the CI indicates that the CI excludes zero, i.e. the speech MDC is significantly larger than the cognitive MDC.}
\label{tab:mdc_bootstrap_cohortB}
\begin{tabular}{lcccccccc}
\toprule
 & \multicolumn{2}{c}{Language} & \multicolumn{2}{c}{Memory} & \multicolumn{2}{c}{Executive Function} & \multicolumn{2}{c}{Speed} \\
 & 95\% CI & \% better & 95\% CI & \% better & 95\% CI & \% better & 95\% CI & \% better \\
\midrule
Journaling & -0.14 -- 2.16 & 93.9\% & -0.35 -- 0.89 & 64.4\% & 0.57 -- 8.55* & 99.9\% & 1.47 -- 81.12* & 100.0\% \\
Cookie Theft & -0.29 -- 1.06 & 81.8\% & 0.09 -- 2.15* & 99.2\% & 0.17 -- 4.35* & 99.0\% & 1.34 -- 41.36* & 100.0\% \\
Picnic Scene & -0.55 -- 0.51 & 39.0\% & -0.24 -- 1.12 & 80.2\% & -0.19 -- 2.14 & 91.3\% & 0.70 -- 15.57* & 100.0\% \\
Avg. Speech Pred. & -0.75 -- 0.24 & 12.9\% & -0.46 -- 0.58 & 37.5\% & -0.29 -- 2.05 & 85.4\% & 0.65 -- 31.16* & 100.0\% \\
\bottomrule
\end{tabular}
\end{table}

In [14]:
import numpy as np
import pandas as pd

TASK_ORDER = ['journaling', 'cookieTheft', 'picnicScene', 'avg_speech_prediction']
TASK_DISPLAY = {
    'cookieTheft': 'Cookie Theft',
    'picnicScene': 'Picnic Scene',
    'journaling': 'Journaling',
    'avg_speech_prediction': 'Avg. Speech Pred.',
}
DOMAIN_ORDER = ['language', 'memory', 'executive_function',  'speed']
DOMAIN_DISPLAY = {
    'executive_function': 'Executive Function',
    'language': 'Language',
    'memory': 'Memory',
    'speed': 'Speed',
}

N_BOOTSTRAP_SAMPLES = 10000  # adjust to match your n_bootsrap_samples
ALPHA = 0.05                 # threshold for flagging the non-inferiority p value
P_MARK = r'$^{\dagger}$'     # marker appended when p < ALPHA (non-inferiority established)

# Rows of `combined` that carry the numbers we need, e.g.
#   'journaling_bootstrap_ci_low'  or  'journaling_noninferiority_p_value'
_ROW_PATTERN = r'^(?P<task>.+?)_(?P<block>bootstrap|noninferiority)_(?P<metric>.+)$'

_FLOAT_COLS = [
    'mean_diff', 'ci_low', 'ci_high', 'prop_speech_worse',
    'ni_margin', 'ni_ci_low', 'ni_ci_high', 'ni_p_value',
]


def _melt_combined(combined):
    """Reshape `combined` from
        index = '<task>_bootstrap_<metric>' / '<task>_noninferiority_<metric>',
        columns = (domain, cohort)
    to a long dataframe with columns
        cohort, domain, task, mean_diff, ci_low, ci_high, excludes_zero,
        prop_speech_worse, ni_margin, ni_ci_low, ni_ci_high, ni_p_value.

    Non-inferiority metrics are prefixed with 'ni_' so they cannot collide with
    the bootstrap ones; every other row of `combined` is ignored.
    """
    # Split the row index into (task, block, metric); drop rows we do not model.
    parsed = combined.index.to_series().str.extract(_ROW_PATTERN)
    keep = parsed['task'].notna().to_numpy()

    tmp = combined.loc[keep].copy()
    task = parsed.loc[keep, 'task'].to_numpy()
    block = parsed.loc[keep, 'block'].to_numpy()
    metric = parsed.loc[keep, 'metric'].to_numpy()
    metric = np.where(block == 'noninferiority', np.char.add('ni_', metric.astype(str)), metric)
    tmp.index = pd.MultiIndex.from_arrays([task, metric], names=['task', 'metric'])

    # Long form: one row per (task, metric, domain, cohort).
    long = tmp.stack(level=[0, 1], future_stack=True).rename('value').reset_index()
    long.columns = ['task', 'metric', 'domain', 'cohort', 'value']

    # Pivot metrics into columns.
    wide = long.pivot_table(
        index=['cohort', 'domain', 'task'],
        columns='metric',
        values='value',
        aggfunc='first',
    ).reset_index()
    wide.columns.name = None

    # Types. Metrics that are absent (e.g. no non-inferiority test run) become NaN.
    for c in ['excludes_zero'] + _FLOAT_COLS:
        if c not in wide.columns:
            wide[c] = np.nan
    wide['excludes_zero'] = (
        wide['excludes_zero'].replace("True", 1).replace("False", 0).fillna(0).astype(bool)
    )
    for c in _FLOAT_COLS:
        wide[c] = pd.to_numeric(wide[c], errors='coerce')
    return wide


def _fmt_ci(row):
    s = f"{row['ci_low']:.2f} -- {row['ci_high']:.2f}"
    if row['excludes_zero']:
        s += '*'
    return s


def _fmt_prop(p):
    return f"{p:.1%}".replace('%', r'\%')


def _fmt_p(p, alpha=ALPHA):
    """Format the one-sided non-inferiority p value; flag it when p < alpha."""
    if pd.isna(p):
        return '--'
    s = r'$<0.001$' if p < 0.001 else f'{p:.3f}'
    if p < alpha:
        s += P_MARK
    return s


def _build_cohort_wide(long_df, cohort_label):
    """Build the (task x (domain, metric)) wide table for a single cohort."""
    sub = long_df[
        (long_df['cohort'] == f'Cohort {cohort_label}')
        & (long_df['task'].isin(TASK_ORDER))
    ].copy()
    sub['ci_str'] = sub.apply(_fmt_ci, axis=1)
    sub['prop_str'] = sub['prop_speech_worse'].apply(_fmt_prop)
    sub['p_str'] = sub['ni_p_value'].apply(_fmt_p)

    pieces = []
    for domain in DOMAIN_ORDER:
        d = (
            sub[sub['domain'] == domain]
            .set_index('task')[['ci_str', 'prop_str', 'p_str']]
        )
        d.columns = pd.MultiIndex.from_tuples([
            (DOMAIN_DISPLAY[domain], r'95\% CI'),
            (DOMAIN_DISPLAY[domain], r'\% larger'),
            (DOMAIN_DISPLAY[domain], r'$p_{\mathrm{NI}}$'),
        ])
        pieces.append(d)

    wide = pd.concat(pieces, axis=1).loc[TASK_ORDER]
    wide.index = [TASK_DISPLAY[t] for t in wide.index]
    wide.index.name = None
    return wide


def _get_margin(long_df, cohort_label):
    """The non-inferiority margin used for this cohort (None if not unique)."""
    m = long_df.loc[long_df['cohort'] == f'Cohort {cohort_label}', 'ni_margin'].dropna().unique()
    return float(m[0]) if len(m) == 1 else None


def cohort_to_latex(wide, cohort_label, n_bootstrap=N_BOOTSTRAP_SAMPLES, margin=None, alpha=ALPHA):
    column_format = 'l' + 'c' * wide.shape[1]
    body = wide.to_latex(
        column_format=column_format,
        multicolumn=True,
        multicolumn_format='c',
        escape=False,
    )
    margin_str = f"{margin:g}" if margin is not None else "the pre-specified margin"
    caption = (
        f"Bootstrap test results assessing whether the speech-based MDC is significantly larger "
        f"than the cognitive assessment's MDC on Cohort {cohort_label}. For each task and composite "
        f"cognitive score, we report the 95\\% CI of the difference (speech MDC minus cognitive MDC) "
        f"across {n_bootstrap} bootstrap replicates, the proportion of replicates where the speech "
        f"MDC is larger (less sensitive) than the cognitive MDC (\\% larger), and the one-sided "
        f"bootstrap p value of the non-inferiority test ($p_{{\\mathrm{{NI}}}}$) against a margin of "
        f"{margin_str}. An asterisk (*) on the CI indicates that the CI excludes zero, i.e. the speech "
        f"MDC is significantly larger than the cognitive MDC. A dagger ($\\dagger$) on "
        f"$p_{{\\mathrm{{NI}}}}$ indicates $p<{alpha:g}$, i.e. the speech MDC is significantly "
        f"non-inferior to the cognitive MDC at the {margin_str} margin."
    )
    label = f"tab:mdc_bootstrap_cohort{cohort_label}"
    return (
        "\\begin{table}\n"
        f"\\caption{{{caption}}}\n"
        f"\\label{{{label}}}\n"
        f"{body}"
        "\\end{table}\n"
    )


# --- Usage ---------------------------------------------------------------
long_df = _melt_combined(combined)
for cohort in ['A', 'B']:
    wide = _build_cohort_wide(long_df, cohort)
    print(f"\n% === Cohort {cohort}: MDC stats for all composite scores ({now()}) ===")
    print(cohort_to_latex(wide, cohort, margin=_get_margin(long_df, cohort)))

% === Cohort A: MDC stats for all composite scores (2026-09-22 11:28) ===
\begin{table}
\caption{Bootstrap test results assessing whether the speech-based MDC is significantly larger than the cognitive assessment's MDC on Cohort A. For each task and composite cognitive score, we report the 95\% CI of the difference (speech MDC minus cognitive MDC) across 10000 bootstrap replicates, the proportion of replicates where the speech MDC is larger (less sensitive) than the cognitive MDC (\% larger), and the one-sided bootstrap p value of the non-inferiority test ($p_{\mathrm{NI}}$) against a margin of 0.5. An asterisk (*) on the CI indicates that the CI excludes zero, i.e. the speech MDC is significantly larger than the cognitive MDC. A dagger ($\dagger$) on $p_{\mathrm{NI}}$ indicates $p<0.05$, i.e. the speech MDC is significantly non-inferior to the cognitive MDC at the 0.5 margin.}
\label{tab:mdc_bootstrap_cohortA}
\begin{tabular}{lcccccccccccc}
\toprule
 & \multicolumn{3}{c}{Language} & \multicolumn{3}{c}{Memory} & \multicolumn{3}{c}{Executive Function} & \multicolumn{3}{c}{Speed} \\
 & 95\% CI & \% larger & $p_{\mathrm{NI}}$ & 95\% CI & \% larger & $p_{\mathrm{NI}}$ & 95\% CI & \% larger & $p_{\mathrm{NI}}$ & 95\% CI & \% larger & $p_{\mathrm{NI}}$ \\
\midrule
Journaling & 0.69 -- 2.27* & 100.0\% & -- & 0.58 -- 2.68* & 100.0\% & 0.985 & 1.20 -- 3.18* & 100.0\% & 0.999 & 2.23 -- 6.29* & 100.0\% & 1.000 \\
Cookie Theft & 0.37 -- 1.73* & 100.0\% & -- & 0.27 -- 1.68* & 99.9\% & 0.847 & 1.18 -- 3.20* & 100.0\% & 1.000 & 2.44 -- 6.44* & 100.0\% & 1.000 \\
Picnic Scene & -0.06 -- 0.94 & 95.4\% & -- & -0.10 -- 1.20 & 93.6\% & 0.411 & 0.55 -- 1.83* & 100.0\% & 0.982 & 1.46 -- 3.51* & 100.0\% & 1.000 \\
Avg. Speech Pred. & -0.28 -- 0.59 & 73.6\% & -- & -0.33 -- 0.74 & 62.7\% & 0.087 & 0.18 -- 1.33* & 99.9\% & 0.741 & 1.11 -- 3.28* & 100.0\% & 1.000 \\
\bottomrule
\end{tabular}
\end{table}


% === Cohort B: MDC stats for all composite scores (2026-09-22 11:28) ===
\begin{table}
\caption{Bootstrap test results assessing whether the speech-based MDC is significantly larger than the cognitive assessment's MDC on Cohort B. For each task and composite cognitive score, we report the 95\% CI of the difference (speech MDC minus cognitive MDC) across 10000 bootstrap replicates, the proportion of replicates where the speech MDC is larger (less sensitive) than the cognitive MDC (\% larger), and the one-sided bootstrap p value of the non-inferiority test ($p_{\mathrm{NI}}$) against a margin of 0.5. An asterisk (*) on the CI indicates that the CI excludes zero, i.e. the speech MDC is significantly larger than the cognitive MDC. A dagger ($\dagger$) on $p_{\mathrm{NI}}$ indicates $p<0.05$, i.e. the speech MDC is significantly non-inferior to the cognitive MDC at the 0.5 margin.}
\label{tab:mdc_bootstrap_cohortB}
\begin{tabular}{lcccccccccccc}
\toprule
 & \multicolumn{3}{c}{Language} & \multicolumn{3}{c}{Memory} & \multicolumn{3}{c}{Executive Function} & \multicolumn{3}{c}{Speed} \\
 & 95\% CI & \% larger & $p_{\mathrm{NI}}$ & 95\% CI & \% larger & $p_{\mathrm{NI}}$ & 95\% CI & \% larger & $p_{\mathrm{NI}}$ & 95\% CI & \% larger & $p_{\mathrm{NI}}$ \\
\midrule
Journaling & -0.14 -- 2.16 & 93.9\% & -- & -0.35 -- 0.89 & 64.4\% & 0.127 & 0.57 -- 8.55* & 99.9\% & 0.981 & 1.47 -- 81.12* & 100.0\% & 0.999 \\
Cookie Theft & -0.29 -- 1.06 & 81.8\% & -- & 0.09 -- 2.15* & 99.2\% & 0.735 & 0.17 -- 4.35* & 99.0\% & 0.892 & 1.34 -- 41.36* & 100.0\% & 0.999 \\
Picnic Scene & -0.55 -- 0.51 & 39.0\% & -- & -0.24 -- 1.12 & 80.2\% & 0.193 & -0.19 -- 2.14 & 91.3\% & 0.579 & 0.70 -- 15.57* & 100.0\% & 0.993 \\
Avg. Speech Pred. & -0.75 -- 0.24 & 12.9\% & -- & -0.46 -- 0.58 & 37.5\% & 0.035$^{\dagger}$ & -0.29 -- 2.05 & 85.4\% & 0.465 & 0.65 -- 31.16* & 100.0\% & 0.986 \\
\bottomrule
\end{tabular}
\end{table}

In [15]:
# results of non-inferiority test for non-signiifcant differences

def ni_p_table(long_df, cohort):
    sub = long_df[(long_df['cohort'] == f'Cohort {cohort}') & ~long_df['excludes_zero']]
    tab = (
        sub.pivot(index='task', columns='domain', values='ni_p_value')
        .reindex(index=TASK_ORDER, columns=DOMAIN_ORDER)
        .rename(index=TASK_DISPLAY, columns=DOMAIN_DISPLAY)
        .dropna(how='all')
        .dropna(axis=1, how='all')
        .round(3)
    )
    return tab

for c in ['A', 'B']:
    #display(ni_p_table(long_df, c))
    pass



def ni_p_latex(tab, cohort, margin=0.5, alpha=0.05):
    tab = tab.copy()
    tab.index.name = None
    tab.columns.name = None
    def format_pval(p):
        return r'$<0.001$*' if p < 0.001 else f'{p:.3f}' + ('*' if p < alpha else '')
    caption = (
        f"Non-inferiority $p$-values for Cohort {cohort}, restricted to the combinations of speech task and composite score where speech-based and cognitive MDC were not significantly different. Significant test results ($p$-value $<0.05$, marked with an asterisk [*]) indicate that the speech MDC is as sensitive as the cognitive MDC at a margin of {margin:g}."
    )
    body = tab.to_latex(
        column_format='l' + 'c' * tab.shape[1],
        float_format=format_pval,
        na_rep='',
        caption=caption,
        label=f's_tab:noninferiority_cohort{cohort}',
    )

    return (
        f"% === Cohort {cohort}: non-inferiority p values (margin {margin:g}, alpha {alpha:g}, {now()}) ===\n"
        f"{body}"
    )

for c in ['A', 'B']:
    print(ni_p_latex(ni_p_table(long_df, c), c))

% === Cohort A: non-inferiority p values (margin 0.5, alpha 0.05, 2026-09-22 11:28) ===
\begin{table}
\caption{Non-inferiority $p$-values for Cohort A, restricted to the combinations of speech task and composite score where speech-based and cognitive MDC were not significantly different. Significant test results ($p$-value $<0.05$, marked with an asterisk [*]) indicate that the speech MDC is as sensitive as the cognitive MDC at a margin of 0.5.}
\label{s_tab:noninferiority_cohortA}
\begin{tabular}{lc}
\toprule
 & Memory \\
\midrule
Picnic Scene & 0.411 \\
Avg. Speech Pred. & 0.087 \\
\bottomrule
\end{tabular}
\end{table}

% === Cohort B: non-inferiority p values (margin 0.5, alpha 0.05, 2026-09-22 11:28) ===
\begin{table}
\caption{Non-inferiority $p$-values for Cohort B, restricted to the combinations of speech task and composite score where speech-based and cognitive MDC were not significantly different. Significant test results ($p$-value $<0.05$, marked with an asterisk [*]) indicate that the speech MDC is as sensitive as the cognitive MDC at a margin of 0.5.}
\label{s_tab:noninferiority_cohortB}
\begin{tabular}{lcc}
\toprule
 & Memory & Executive Function \\
\midrule
Journaling & 0.127 &  \\
Picnic Scene & 0.193 & 0.579 \\
Avg. Speech Pred. & 0.035* & 0.465 \\
\bottomrule
\end{tabular}
\end{table}