In [1]:
import pandas as pd

acs_outliers_removed_2024 = pd.read_csv("/Users/jheitz/git/luha-prolific-study/data/processed_combined/data/acs_outcomes_outliers_removed.csv")
acs_outliers_removed_2026 = pd.read_csv("/Users/jheitz/git/luha-prolific-study/data2026/processed_combined/data/acs_outcomes_outliers_removed.csv")

relevant_tests = {
    'connect_the_dots_I_time_msec': 'Trail Making Test A',
    'connect_the_dots_II_time_msec': 'Trail Making Test B',
    'wordlist_correct_words': 'RAVLT (Learning)',
    'wordlist_delayed_correct_words': 'RAVLT (Recall)',
    'wordlist_recognition_correct_words': 'RAVLT (Recognition)',
    'avg_reaction_speed': 'Visual Reaction Time',
    'box_tapping_total_time': 'Corsi Block-tapping Test',
    'fill_the_grid_total_time': 'Grooved Pegboard',
    'digit_sequence_1_correct_series': 'Digit Span (forward)',
    'digit_sequence_2_correct_series': 'Digit Span (backward)',
    'clickskill_time': 'Clicking speed test',
    'dragskill_time': 'Mouse dragging speed test'
}

In [2]:
cols =list(acs_outliers_removed_2024.columns)
[c for c in cols if 'wordlist' in c]

['wordlist_correct_words',
 'wordlist_delayed_correct_words',
 'wordlist_recognition_correct_words',
 'wordlist_correct_trial1',
 'wordlist_correct_trial2',
 'wordlist_correct_trial3',
 'wordlist_correct_trial4',
 'wordlist_correct_trial5',
 'wordlist_learning',
 'wordlist_total_time',
 'wordlist_delayed_total_time',
 'wordlist_recognition_total_time']

In [3]:
missing_count_2024 = acs_outliers_removed_2024[relevant_tests.keys()].isna().sum()
missing_count_2026 = acs_outliers_removed_2026[relevant_tests.keys()].isna().sum()
total_count_2024 = acs_outliers_removed_2024.shape[0]
total_count_2026 = acs_outliers_removed_2026.shape[0]
stats = pd.DataFrame({'2024': missing_count_2024, '2026': missing_count_2026, 'total_2024': total_count_2024, 'total_2026': total_count_2026})
stats

                                    2024  2026  total_2024  total_2026
connect_the_dots_I_time_msec          15     4        1003         478
connect_the_dots_II_time_msec         23     4        1003         478
wordlist_correct_words                 6     0        1003         478
wordlist_delayed_correct_words         4     0        1003         478
wordlist_recognition_correct_words    13     8        1003         478
avg_reaction_speed                    39     8        1003         478
box_tapping_total_time                 0     0        1003         478
fill_the_grid_total_time              30    13        1003         478
digit_sequence_1_correct_series        6     1        1003         478
digit_sequence_2_correct_series        4     0        1003         478
clickskill_time                       25    12        1003         478
dragskill_time                        26     8        1003         478

In [22]:
stats_combined = pd.DataFrame({'# Outliers': missing_count_2024 + missing_count_2026, '# Assessments': total_count_2024 + total_count_2026})
stats_combined['Outlier percentage'] = (stats_combined['# Outliers'] / stats_combined['# Assessments'] * 100).apply(lambda x: f"{x:.2f}%")
stats_combined.index.name = "Cognitive Test"
stats_combined = stats_combined.rename(index=relevant_tests)
stats_combined

                           # Outliers  # Assessments Outlier percentage
Cognitive Test
Trail Making Test A                19           1481              1.28%
Trail Making Test B                27           1481              1.82%
RAVLT (Learning)                    6           1481              0.41%
RAVLT (Recall)                      4           1481              0.27%
RAVLT (Recognition)                21           1481              1.42%
Visual Reaction Time               47           1481              3.17%
Corsi Block-tapping Test            0           1481              0.00%
Grooved Pegboard                   43           1481              2.90%
Digit Span (forward)                7           1481              0.47%
Digit Span (backward)               4           1481              0.27%
Clicking speed test                37           1481              2.50%
Mouse dragging speed test          34           1481              2.30%

In [23]:
stats_combined = stats_combined[stats_combined.index != 'Overall']
overall_statistic = pd.DataFrame({'# Outliers': [stats_combined['# Outliers'].sum()], '# Assessments': [stats_combined['# Assessments'].sum()]})
overall_statistic['Outlier percentage'] = (overall_statistic['# Outliers'] / overall_statistic['# Assessments'] * 100).apply(lambda x: f"{x:.2f}%")
overall_statistic.index = ['Overall']

stats_combined = pd.concat([stats_combined, overall_statistic])
stats_combined

                           # Outliers  # Assessments Outlier percentage
Trail Making Test A                19           1481              1.28%
Trail Making Test B                27           1481              1.82%
RAVLT (Learning)                    6           1481              0.41%
RAVLT (Recall)                      4           1481              0.27%
RAVLT (Recognition)                21           1481              1.42%
Visual Reaction Time               47           1481              3.17%
Corsi Block-tapping Test            0           1481              0.00%
Grooved Pegboard                   43           1481              2.90%
Digit Span (forward)                7           1481              0.47%
Digit Span (backward)               4           1481              0.27%
Clicking speed test                37           1481              2.50%
Mouse dragging speed test          34           1481              2.30%
Overall                           249          17772              1.40%

In [24]:
from datetime import datetime
now = lambda: datetime.now().strftime("%Y-%m-%d %H:%M")
print("%", now())
print(stats_combined.to_latex(index=True, caption="Number and percentage of individual ACS test scores marked as outliers and subsequently imputed, across all 1481 assessments.", label="s_tab:outliers_cognitive_tests", float_format="%.0f").replace("%", "\\%").replace("#", "\\#"))

% 2026-09-17 15:08
\begin{table}
\caption{Number and percentage of individual ACS test scores marked as outliers and subsequently imputed, across all 1481 assessments.}
\label{s_tab:outliers_cognitive_tests}
\begin{tabular}{lrrl}
\toprule
 & \# Outliers & \# Assessments & Outlier percentage \\
\midrule
Trail Making Test A & 19 & 1481 & 1.28\% \\
Trail Making Test B & 27 & 1481 & 1.82\% \\
RAVLT (Learning) & 6 & 1481 & 0.41\% \\
RAVLT (Recall) & 4 & 1481 & 0.27\% \\
RAVLT (Recognition) & 21 & 1481 & 1.42\% \\
Visual Reaction Time & 47 & 1481 & 3.17\% \\
Corsi Block-tapping Test & 0 & 1481 & 0.00\% \\
Grooved Pegboard & 43 & 1481 & 2.90\% \\
Digit Span (forward) & 7 & 1481 & 0.47\% \\
Digit Span (backward) & 4 & 1481 & 0.27\% \\
Clicking speed test & 37 & 1481 & 2.50\% \\
Mouse dragging speed test & 34 & 1481 & 2.30\% \\
Overall & 249 & 17772 & 1.40\% \\
\bottomrule
\end{tabular}
\end{table}